version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/images:/app/static/images
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
